server:
  port: 8087

spring:
  application:
    name: order

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka
info:
  app:
    name: order
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
