server:
  port: 8082

spring:
  application:
    name: consumer

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

info:
  app:
    name: consumer
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 加了这个 feign就可以调用了
feign:
  hystrix:
    enabled: true
  httpclient:
    connection-timeout: 60000