server:
  port: 8085

spring:
  application:
    name: provider

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/

