server:
  port: 9002

spring:
  application:
    name: provider

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8081/eureka/

info:
  app:
    name: provider
    version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 加解密使用的秘钥
jasypt:
  encryptor:
    password: kither

my:
  password: ENC(f3zHTMgu+5hDxOU+pLYTnw==) # 加密后的密码，原密码为 w23456
